// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4UFSsdG4IckfkSeFUNQnEyJymox3qAmw',
    appId: '1:256687964906:web:f1ac9d42c97cbe6a18cd93',
    messagingSenderId: '256687964906',
    projectId: 'chatapp-b57cb',
    authDomain: 'chatapp-b57cb.firebaseapp.com',
    storageBucket: 'chatapp-b57cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu2KkC_86ZoBT-J3Q6LBgG5RcrMdRAmXg',
    appId: '1:256687964906:android:d50e1526be86536518cd93',
    messagingSenderId: '256687964906',
    projectId: 'chatapp-b57cb',
    storageBucket: 'chatapp-b57cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiByK3U-bj04s3m3HEmSuEE8n3r71gNeE',
    appId: '1:256687964906:ios:fdca86ec006089b018cd93',
    messagingSenderId: '256687964906',
    projectId: 'chatapp-b57cb',
    storageBucket: 'chatapp-b57cb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiByK3U-bj04s3m3HEmSuEE8n3r71gNeE',
    appId: '1:256687964906:ios:fdca86ec006089b018cd93',
    messagingSenderId: '256687964906',
    projectId: 'chatapp-b57cb',
    storageBucket: 'chatapp-b57cb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4UFSsdG4IckfkSeFUNQnEyJymox3qAmw',
    appId: '1:256687964906:web:9b698524a94abf5c18cd93',
    messagingSenderId: '256687964906',
    projectId: 'chatapp-b57cb',
    authDomain: 'chatapp-b57cb.firebaseapp.com',
    storageBucket: 'chatapp-b57cb.appspot.com',
  );
}
